apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  jmx-exporter.yaml: |
    startDelaySeconds: 0
    hostPort: 127.0.0.1:1099
    rules:
      - pattern: ".*"
