apiVersion: v1
kind: Service
metadata:
  name: was-service
  labels:
    app: was
spec:
  selector:
    app: was
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: jmx
      port: 9404
      targetPort: 9404