apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: was-svc-m
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: was
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
