apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      serviceAccountName: ayvet-dev-ksa
      containers:
      - name: was
        image: "{{ .Values.was.image.repository }}:{{ .Values.was.image.tag }}"
        ports:
        - containerPort: 8080
        - containerPort: 1099
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
              
      - name: cloudsql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.0
        args:
          - "--structured-logs"
          - "--port=3306"
          - "--private-ip"
          - "kdt1-finalproject:asia-northeast3:ayvet-dev-db"
        securityContext:
          runAsNonRoot: true
      - name: jmx-exporter
        image: bitnami/jmx-exporter:1.3.0
        ports:
        - containerPort: 9404
        volumeMounts:
        - name: jmx-config
          mountPath: /config
        args:
        - "--config.file=/config/jmx-exporter.yaml"
        - "127.0.0.1:1099"
      volumes:
        - name: jmx-config
          configMap:
            name: jmx-config
            items:
              - key: jmx-exporter.yaml
                path: jmx-exporter.yaml